name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["feature"]
assignees: ""
body:
  - type: textarea
    id: feature-description
    attributes:
      label: 功能描述
      description: 请清晰、简洁地描述您想要的功能。
      placeholder: 例如：添加用户头像上传功能
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 动机
      description: 请解释为什么这个功能很重要，它能解决什么问题？
      placeholder: 例如：当前用户无法自定义头像，影响用户体验
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 请描述实现此功能后预期会发生的行为。
      placeholder: 例如：用户可以上传、裁剪和更换头像
    validations:
      required: true

  - type: textarea
    id: implementation-suggestions
    attributes:
      label: 实现建议
      description: 如果您有任何关于如何实现此功能的建议，请在此处列出。
      placeholder: 例如：可以使用AWS S3存储用户头像，前端使用Cropper.js进行裁剪
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 请描述您考虑过的任何替代解决方案或功能。
      placeholder: 例如：可以使用第三方头像服务如Gravatar
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: 附加信息
      description: 添加任何其他相关信息，如截图、示例等。
      placeholder: 例如：可以参考这个设计稿 https://example.com/design
    validations:
      required: false
